### ISSUE TITLE
.mtn2 export bloats filesize

### ISSUE THREAD

**Issue by asteriddle** [Tiniifan/studio_eleven#10]
**The issue:**
When exporting an animation as .mtn2, the file's size is exponentially larger than the base animations. Even importing a base game animation and re-exporting it will yield this result.

This becomes an issue when accounting for the fact that, as 3DS games, many L5 games have some form of memory management, even when emulated. If the file size of an animation (or other unrelated model asset) is too large, the game will start to display a buggy UI in an attempt to conserve memory - or will straight up crash on hardware.

Provided are three sample files in the ZIP (Github won't let me upload them raw);
[studioeleven mtn2 issue samplefiles.zip](https://github.com/user-attachments/files/16058852/studioeleven.mtn2.issue.samplefiles.zip)

These sample files were created based around resources in Yokai Watch 2: Psychic specters

**bakulia og mtn2 000.mtn2** - The original, unmodded .mtn2 for Bakulia's p20.xc file, mostly for reference.
**p20 bakulia reexport.mtn2** - This is the exact same motion as above, but it has been imported into Blender with Studio Eleven and then exported with no changes.
**p20 complete custom.mtn2** - This is a completely custom .mtn2 that uses my own model's skeleton, though the start and end frames for actions and length of the timeline are the same.

**Comment by Tiniifan** [comment]
Hello.

I've analyzed the problem of abnormally large file sizes after the export process, it seems that the XMTN exporter exports frame by frame for each bone, it doesn't ignore empty frames or bones that have no motion data. 
Example: if you have an animation with1000 frames and 30 bones you have 90000 data (1000*30*3, 3 represents location, scale and rotate). This problem will be fixed in the next update (it was already planned to update the XMTN).

However, this problem may not solve your problem about the game being corrupted, because even if the files are heavy, your file isn't heavy enough to oversize the game memory, this problem comes from the tool you use to replace your files in the .fa which tends to corrupt .fa files for no reason after many modifications

**Comment by Tiniifan** [comment]
Hi, the problem was solved in the [latest release](https://github.com/Tiniifan/studio_eleven/releases/tag/1.1.1)

Thank for reporting the issue, I'm closing the issue

**Comment by Tiniifan** [comment]
The latest release broke the ykw template so this issue is reopened until there is a release that fixes this problem even if this problem is already considered solved because studio_eleven 1.2.0 will add the mtn player improvement from [Fougere ](https://github.com/Tiniifan/Fougere)

**Comment by Tiniifan** [comment]
Hi, thanks you for reporting the problem. We fixed it! 
The problem came from a misunderstanding of blender:
- every bone was written to the file (even if it had no transformation) 
- the code looped on each frame when it should loop on each fcurve 
![image](https://github.com/user-attachments/assets/887d4d53-ed71-40ee-a740-ebaf2c9a18e7)

I'm closing this issue, the fix will be applied in the next version.
